server:
  port: 9100

spring:
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://auth-server:9000/oauth2/jwks

logging:
  level:
    root: INFO
    com.scg.service: INFO
    org.springframework.web: INFO
    org.springframework.web.HttpLogging: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
